name: Test on Push and Pull Request

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Change working directory
      run: cd /home/runner/work/Grocery-Store/Grocery-Store

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set Python path
      run: export PYTHONPATH=$PYTHONPATH:/home/runner/work/Grocery-Store/Grocery-Store
      
    - name: Run tests
      run: pytest
